pipeline {

 agent any

 environment {
   DOCKER_IMAGE = "shivdevops/devops-app"
 }

 stages {

  stage('Clone Repo') {
 steps {
  git branch: 'main', url: 'https://github.com/Shiva202-27/devops-production-project.git'
 }
}

  
 stage('Build Docker Image') {
 steps {
  sh 'docker build -t $DOCKER_IMAGE -f docker/Dockerfile .'
 }
}

  stage('Deploy to Kubernetes') {
   steps {
    sh 'kubectl apply -f kubernetes/'
   }
  }

 }

}
