pipeline {

 agent any

 environment {
   DOCKER_IMAGE = "shivdevops/devops-app"
 }

 stages {

  stage('Clone Repo') {
   steps {
    git 'https://github.com/Shiva202-27/devops-production-project.git'
   }
  }

  stage('Build Docker Image') {
   steps {
    sh 'docker build -t $DOCKER_IMAGE .'
   }
  }

  stage('Push Image') {
   steps {
    sh 'docker push $DOCKER_IMAGE'
   }
  }

  stage('Deploy to Kubernetes') {
   steps {
    sh 'kubectl apply -f kubernetes/'
   }
  }

 }

}
